# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # NPM packages
  - package-ecosystem: "npm"
    directory: "/" # Root of the project
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "LeonardoLAraujo"
      - "rounknow"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Root of the project
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    reviewers:
      - "LeonardoLAraujo"
      - "rounknow"
